### ISSUE TITLE
Create new file when file dont exists

### ISSUE THREAD

**Issue by otavioschwanck** [nvim-telescope/telescope-file-browser.nvim#114]
Would be nice to have an option when i type the name of file:

i type:
>> my_file.js

On telescope:
__________
[+] my_file.js (new file)
../
__________

and when i select this option, it create a file and opens on editor.

Emacs do it and its awesome.

**Comment by fdschmidt93** [comment]
I'll leave this here for context.

https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/104#issuecomment-1049647208
https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/78#issuecomment-1018819041

You can pretty straightforwardly come up with your own lua function to achieve something along these lines. Holistic support from `telescope-file-browser.nvim` is very difficult due to the  async nature of telescope.

**Comment by fdschmidt93** [comment]
I've realized this probably is probably a bit of a separate issue and quickly implemented it. It should now work as desired I hope.
