### ISSUE TITLE
How to remove files without prompt?

### ISSUE THREAD

**Issue by rzksobhy78** [nvim-telescope/telescope-file-browser.nvim#13]
how can I remove files without this prompt

or at least make it easier by just pressing y for yes or n no
and no additional need to press one more enter

![Tue Dec  7 22:05:37 EET 2021](https://user-images.githubusercontent.com/94202082/145098500-58a436dc-b1e7-422f-8007-d91ee38db2f3.png)

**Comment by fdschmidt93** [comment]
You cannot change that with the default implementation, as that one relies on `vim.fn.inputlist` which produces the kind of selection via numbers as you see in your prompt.

Consequently, the most straightforward answer would be to use a different custom handler for `vim.ui.select` eg https://github.com/nvim-telescope/telescope-ui-select.nvim

However, `telescope-ui-select.nvim` does not block, which might cause issues in case you customize LSP handlers that require blocking up until you confirm the selection.

I'll leave the issue open as I'll reconsider this prior to file browser deprecation in telescope-core, though I'm a bit reluctant to switch the code back to `vim.fn.confirm`

**Comment by miguelmoraperea** [comment]
@rzksobhy78 @fdschmidt93 I agree that using numbered options is not ideal, considering there are only 2 options (yes/no) there will never be more, which is why I also prefer the more user-friendly (Y/N) format.

Do you mind testing my latest pull request, that addresses this request, it works like this:

![refactor-delete-file-options](https://user-images.githubusercontent.com/42681212/147721675-fd63f218-6071-4965-a477-8d0b49e1ac4a.gif)

**Comment by fdschmidt93** [comment]
I think this is now sufficiently addressed with #42 

Please let me know in case there's more to do here.
