### ISSUE TITLE
Option to open newly created file?

### ISSUE THREAD

**Issue by davidatsurge** [nvim-telescope/telescope-file-browser.nvim#136]
**Is your feature request related to a problem? Please describe.**
99% of the time, when I create a new file, I would like to edit it immediately. 

**Describe the solution you'd like**
It'd be great if there is an option to open a newly created file automatically in the current window / in a split / in a tab.

**Describe alternatives you've considered**
None.

**Additional context**
None.

PS: Thanks for this plugin!!

**Comment by fdschmidt93** [comment]
> PS: Thanks for this plugin!!

You're welcome! Glad you like it :)

The canonical way to do this would be [fb_actions.create_from_prompt](https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/7861dddeb3102880965bb3720250dd5c3cc5da33/lua/telescope/_extensions/file_browser/actions.lua#L117-L134) which by default is mapped to `<S-CR>` should your terminal support that (see also `:h tui-input`). It works for me perfectly with kitty out of the box.

Otherwise, you can of course always remap that action to any key you like as per the README.

**Comment by fdschmidt93** [comment]
I haven't gotten feedback in quite some time and believe this request is sufficiently served by creating a file from prompt :)

Closing. Please let me know if there's more to discuss here otherwise.
