### ISSUE TITLE
Add documentation on how to select files

### ISSUE THREAD

**Issue by Signynt** [nvim-telescope/telescope-file-browser.nvim#154]
I searched through the help files and the README for half an hour, feeling like I must be an idiot for not finding it, trying to figure out _how_ to select multiple files for the multi selection, and couldn't find it anywhere. I finally found it get mentioned in #123 : you need to press `TAB` on the selected file to add it to the multi selection!
This might be some obvious knowledge to most people, but I have never seen it done that way, so I was exteremely confused.

Please add this to the README or the help files!

**Comment by fdschmidt93** [comment]
> This might be some obvious knowledge to most people, but I have never seen it done that way, so I was extremely confused.

Yes, I would say it is. `telescope-file-browser.nvim` is a `telescope.nvim` extension and those global default mappings apply (across all pickers, whether they are an extension or not). I'm happy to accept a documentation PR to clarify if you feel that should be added. For anyone who's looked appropriately into telescope I feel though this should be known -- IIRC I refer to upstream documentation several times (incl. below).

Also, as per README

> For more information on telescope actions and remappings, see also the [upstream documentation](https://github.com/nvim-telescope/telescope.nvim#default-mappings) and associated vimdocs at :h telescope.defaults.mappings.

Which explicitly refers to telescope.nvim.

> telescope-file-browser.nvim comes with a lot of default mappings for discoverability. You can use telescope's which_key (insert mode: <C-/>, normal mode: ?) to list mappings attached to your picker.

Toggling multi selection pops up there too, albeit it a bit funny name (due to how this works).

**Comment by Signynt** [comment]
Ah, I didn't know `telescope.nvim` was able to select multiple files, so I didn't think to look for that binding upstream!
I missed the part on using `<C-/>` to check the bindings 😬 
I've been looking into Telescope and did a lot of googling around to find an answer to using multi selection, but somehow couldn't find an answer. I think it would be good for the README to at least link to the default mapping of multi selection, since it is referenced a bunch, but I didn't find a direct link (it could very well be that I just missed it).
I'll make a documentation PR for it 👍
