### ISSUE TITLE
"Collapse" directories when a parent directory only contains one child directory (similar to github filebrowser)

### ISSUE THREAD

**Issue by paul-ohl** [nvim-telescope/telescope-file-browser.nvim#158]
I use telescope-file-browser to browse my dotfiles which I manage with gnu/stow. This makes for a big chain of directories which contain only one directory, and it's a bit unefficient to have a picker to select only one option.

The perfect solution would be a 'collapse_directories' option to the already existing list of options to pass to the file_browser picker.

I have considered as an alternative reversing the sorting so that '..' appears last and the cursor is on the folder, which makes you just tap <CR> multiple times until you've reached the last folder in the chain. It works but is far from ideal and prone to error.

**Comment by fdschmidt93** [comment]
> The perfect solution would be a 'collapse_directories' option to the already existing list of options to pass to the file_browser picker.

To clarify, by collapsing you mean, you want that you directly go from the parent directory to the deepest nested directory (since each folder level in between only contains 1 element, the next folder)  in the `file_browser`?

To clarify in advance, for the `folder_browser`, I wouldn't support this within `telescope-file-browser.nvim` itself, but would require an upstream patch to chain sorters (bigger undertaking), and then you'd filter out folders that only contain a single folder.
