### ISSUE TITLE
Is it possible to initialize telescope file browser in normal mode?

### ISSUE THREAD

**Issue by yannxaver** [nvim-telescope/telescope-file-browser.nvim#162]
**Is your feature request related to a problem? Please describe.**

When I run `:Telescope file_browser` vim switches to insert mode. 

**Describe the solution you'd like**

I would like to initialize the file browser and stay in normal mode.

**Comment by fdschmidt93** [comment]
Sure.

`:Telescope file_browser initial_mode=normal` or `:lua require 'telescope'.extensions.file_browser.file_browser { initial_mode = 'normal' }` which can also be passed to extension setup.

**Comment by lionawurscht** [comment]
Hey, I came across this issue while looking for the same function. However, I noticed that, if I call the file browser via the lua function `require 'telescope'.extensions.file_browser.file_browser { path="xyz", initial_mode = 'normal' }` for different folders, the initial_mode settings is only applied the first time. When I call the function a second time with the same settings, only on another path the setting is ignored and I end up in insert mode. Is this expected behavior? Is the file_browser somehow resumed instead of reinitialized? 

If this is not expected I would open a seperate issue ...

Thanks in advance!

**Comment by fdschmidt93** [comment]
Seems to be a separate issue, and I cannot reproduce from what you wrote. Please make sure to fill out the template.

> Is the file_browser somehow resumed instead of reinitialized?

From what you wrote, it's fully reinitialized, though there are situations in which it strictly speaking is resumed (`:Telescope resume` or changing between file & folder browser).
