### ISSUE TITLE
Option for Tree view when depth value is set 

### ISSUE THREAD

**Issue by LamprosPitsillos** [nvim-telescope/telescope-file-browser.nvim#165]
Have the option to view the directories in a tree instead of having to read the whole path to find something.

![filetree_W](https://user-images.githubusercontent.com/61395246/181695989-cc0f1ab1-14dd-4887-8b82-d15557e3bf7f.png)

Something like this but with all the functionality of this plugin!

**Comment by fdschmidt93** [comment]
I don't really follow your requests. There's lots of open questions as to _what exactly_ you actually want to achieve. Please don't be that lazy and make a more comprehensible feature request that discusses:

- UI: how are users exactly supposed to see a tree view (file- or folder-browser), e.g. in results or preview buffer?
- UX: what are potential UX improvements here?

Both aspects I perceive as **very** clean right now in `telescope-file-browser.nvim`. Once users grok switching between file and folder-browsing, I believe speed of execution for even complex file edit operations is not easily matched by more vanilla file explorers.

That said, `neo-tree` can perfectly co-exists with `telescope-file-browser.nvim`.

**Comment by joeyschoblaska** [comment]
I think that @LamprosPitsillos was proposing showing the file browser results as a tree if the depth option is greater than 1. Eg (current UI on the left, proposed UI on the right):

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/29129/189451504-28ba406f-8a00-415d-947e-ae70112f554f.png">

I find the tree view is easier to scan visually and I think it would be a nice option to have. It does get a little tricky because you would still want to be able to fuzzy search on the full path of all files / folders, even though the tree view is hiding part of that path for any nested items.

If this seems feasible I'm happy to take a crack at implementing it.

Thanks for the great plugin!

**Comment by LamprosPitsillos** [comment]
Yes , forgive me for not posting after with a more detailed explanation, but yes , this is exactly what i had in mind!

**Comment by fdschmidt93** [comment]
> If this seems feasible I'm happy to take a crack at implementing it.

Sure, it's feasible. I'm mostly wary of things would have to change to preserve the simple status quo all the while enabling this. You're very happy to take a crack and we'd take things in a PR from there.

> It does get a little tricky because you would still want to be able to fuzzy search on the full path of all files / folders, even though the tree view is hiding part of that path for any nested items.

In principle, this is feasible though telescope wasn't really designed with some of the requirements here in mind (there's some workarounds already in `telescope-file-browser.nvim`). 

At the first tree view, the screenshot looks fine (I suppose some users would like connecting vertical lines, but it's probably a lot more overhead than worthwhile vis-a-vis simple indentation).

When a user starts searching, nested items would require the full relative part (or "smart", etc. as per telescope `path_display`) to visually distinguish between potentially identically named options (`entry.display`). Sorting is a different thing (`entry.ordinal`). All elements are tracked by their absolute path to begin with (`entry.value`). For more reference see

- https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md
- https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/master/lua/telescope/_extensions/file_browser/make_entry.lua

I hope that's sufficient to get you started, happy to answer more questions if needed.

One more note -

```lua
local action_state = require "telescope.actions.state"
local current_picker = action_state.get_current_picker(prompt_buf or vim.api.nvim_get_current_buf())
local prompt = current_picker:_get_prompt()
```
gets you the prompt, to e.g. differentiate when a user is searching or not. There is a very general use case function for this in telescope-file-browser nvim to get the prompt already (`get_fb_prompt`).

**Comment by joeyschoblaska** [comment]
That's massively helpful, thank you!

**Comment by tobealive** [comment]
would love to see this. If nobody is already on this, I should be able to make the time to give it a shot next week.

**Comment by joeyschoblaska** [comment]
@tobealive Go for it! I haven't started on anything, but let me know if you want someone to bounce ideas off of.

**Comment by tobealive** [comment]
Hey @joeyschoblaska,

I wanted to come back real quick to my call about working on this. Unfortunately, I have to admit that putting work into it lost priority. The reason is that I found a satisfying alternative and having a lot of back and forth between two new projects at work.
 
In case someone is interested in the alternative:
As regular tree plugin I'm using neo-tree. For telescope-like file browsing use-cases it can be toggled in floating mode. Additionally, it allows different kinds of filtering, has configurable tree views, previews etc. So it's more than just visualizing tree depth, so it would be quiet some work to catch up with those functionalities. 

_<sub>Please let me know if it's inappropriate to talk about other plugins here, so I can remove the paragraph. </sub>_

Of course eventually - speaking from an end users perspective - it would be super nice to have this feature for telescope-file-browser for an even more uniform experience using telescope directly.

**Comment by jamestrew** [comment]
I'm going to close this consider we closed the PR for this while back.
See more on this https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/210

**Comment by schoblaska** [comment]
This is the route I ended up going: https://github.com/nvim-telescope/telescope.nvim/pull/3052#issuecomment-2113686410
