### ISSUE TITLE
Allow file_browser to display the absolute path at the top of the dialog.

### ISSUE THREAD

**Issue by windowsrefund** [nvim-telescope/telescope-file-browser.nvim#176]
**Is your feature request related to a problem? Please describe.**
For whatever reason, I see folder_browser displays the full path where the file_browser simply displays what is relative. In order to see the absolute path, I have to change to "folder mode" with `C-f`

Honestly, I don't understand why anyone would ever use "folder mode" at all...

**Describe the solution you'd like**
I would like a way to configure file_browser to always show the the absolute path at the top, regardless of what layout is used.

Thanks in advance.

**Comment by fdschmidt93** [comment]
> Honestly, I don't understand why anyone would ever use "folder mode" at all...

To go to or move/copy/remove files/folders from nested folder structures. You should give it a try ;)

If you'd want the feature, I'd encourage you to take over this PR and see my comments from there

https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/155

For the time being, I maintain this project by fixing bugs and from time to time answering questions.

**Comment by windowsrefund** [comment]
Am I missing something here or is it [your PR](https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/73) that's been sitting idle for 8 months?

**Comment by fdschmidt93** [comment]
The PR doesn't do what it appears to me you think it does: It'd enable going to a folder by selecting a file rather than a folder in folder browser mode. It doesn't address

>  I would like a way to configure file_browser to always show the the absolute path at the top, regardless of what layout is used.

What you want to have is I think is discussed in #155 -- I've given my thoughts in [this comment](https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/155#pullrequestreview-1031490884) and I'm encouraging you to take over that PR.

> that's been sitting idle for 8 months?

It's at anyone's liberty (not) to request/contribute -- this is FOSS, after all. As I've mentioned originally, I'm currently happy with `telescope-file-browser.nvim` that I'm these days not working so much on features myself rather than fixing bugs and answering questions. Some PRs are just ideas/concepts you work on.
