### ISSUE TITLE
What is hijack_netrw spposed to do?

### ISSUE THREAD

**Issue by eccentric-j** [nvim-telescope/telescope-file-browser.nvim#180]
I've enabled this option. My understanding was that if I ran commands like :Explore or :Tex it would instead open the file browser UI but in the case of tex still open a new tab.

Instead, I just get an error `Unknown function: netrw#Explore`.

Based on the code:

https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/00a814a891de086ed446151bacc559c63682b6ee/lua/telescope/_extensions/file_browser/config.lua#L85

It seems like that it might be setting vim.g.loaded_netrw and such before netrw activates which provides the backing explore function. This seems like it may be intentional?

If it is intentional, how should I be using this plugin? What's the best way to create a new tab with the file browser open?

**Comment by eccentric-j** [comment]
Looked at the netrc docs:

> PREVENTING LOADING					*netrw-noload*
>
> If you want to use plugins, but for some reason don't wish to use netrw, then
> you need to avoid loading both the plugin and the autoload portions of netrw.
> You may do so by placing the following two lines in your <.vimrc>:  

>	:let g:loaded_netrw       = 1
>	:let g:loaded_netrwPlugin = 1

Which means it's probably my expectations\usage that's wrong here. What's the intended way to use this feature?

**Comment by fdschmidt93** [comment]
> What's the intended way to use this feature?

First off, I'm not responsible for this feature (I'm actually opposed), and the original author has gone AWOL.

I'd be extremely happy for somebody to take over maintenance of this feature (e.g. https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/150). The PR also illustrates why we cannot get rid of netrw entirely. I'm personally simply not interested in this feature at all and tedious issues I'm not in the slightest keen on fixing keep appearing.

> If it is intentional, how should I be using this plugin? 

The intended usage is that for instance `nvim .` opens the file browser instead of netrw in the current folder or that you can do `:e $FOLDER_PATH` to open file_browser as opposed to netrw.

As a hack, you could always create user commands (`vim.api.nvim_create_user_command`) to replace `:Explore` and `:Tex` I suppose as you desire.
Otherwise, why not just do `:Telescope file_browser`? I don't follow as to why you need (or anyone beyond the current functionality of `hijack_netrw`)

**Comment by eccentric-j** [comment]
That's helpful and based on that don't feel I really need this feature. I think I'm fine if nvim . opens in netrw then can choose to invoke `:Telescope file_browser` if I need more than that to pick a file to open.

I take it in general if I wanted to use file_browser, create a new file, and open it in a new tab I would use the create shortcut then the open in tab shortcut?

**Comment by eccentric-j** [comment]
I see thanks! Can take this elsewhere but with find_files it doesn't seem to support moving up a directory. Seems it's mostly helpful for finding files in the current or child directories of cwd. Where as I want to browse the current cwd, then be able to move up or down a dir and sometimes perform file ops which file_browser seems great for.

**Comment by jamestrew** [comment]
Original author of the `hijack_netrw` feature :wave: 
Frankly, despite my initial initiative, I've never been a user of this feature either. My thoughts originally was there were a group of users, people curious about this telescope extension who were coming from places like `nvim-tree` which has similar options. I think some people find netwr's Explorer cumbersome to use and if they're going to be using `:Telescope file_browser`, they'd rather that open on startup.

I'll follow up on #150

**Comment by jbsilva** [comment]
> Original author of the `hijack_netrw` feature wave Frankly, despite my initial initiative, I've never been a user of this feature either. My thoughts originally was there were a group of users, people curious about this telescope extension who were coming from places like `nvim-tree` which has similar options. I think some people find netwr's Explorer cumbersome to use and if they're going to be using `:Telescope file_browser`, they'd rather that open on startup.
> 
> I'll follow up on #150

Yeah, this is exactly my case.
