### ISSUE TITLE
Automatically increase depth when searching

### ISSUE THREAD

**Issue by rizo** [nvim-telescope/telescope-file-browser.nvim#200]
**Is your feature request related to a problem? Please describe.**
I would be great to have a simple folder view when navigating with arrows/enter, but automatically switch a deep search mode when typing in the picker.

**Describe the solution you'd like**
Use default depth unless the user types something in the prompt. At that point allow searching for nested files and folders (relative to the currently opened folder). When the user deletes the content of the prompt, revert back to the folder view.

**Describe alternatives you've considered**
I considered binding a different key for different modes, but I think it would be great to have a single view that does both things. There's no conflict and this would allow for both exploring and finding files very efficiently.

Happy to help with the implementation and/or testing!

**Comment by fdschmidt93** [comment]
Sure, this sounds quite doable and like a cool feature. I'm happy to guide you towards a PR since I probably won't implement this myself (I'm happy with current functionality and already enough preoccupied with work these days). I'd gladly sketch what needs to be done towards the end of the week though if you're up for it.

**Comment by rizo** [comment]
Hi @fdschmidt93! Sounds great – do let me know what you think is the best place to start.
