### ISSUE TITLE
A way to sort files in the `File Preview`

### ISSUE THREAD

**Issue by heygarrett** [nvim-telescope/telescope-file-browser.nvim#201]
**Is your feature request related to a problem? Please describe.**
Files listed in the `File Preview` are not sorted alphabetically, and there doesn't seem to be a way to specify how they should be sorted.

<img width="1440" alt="CleanShot 2022-12-17 at 12 59 31@2x" src="https://user-images.githubusercontent.com/1154912/208255186-16497669-8a17-45fe-be40-d1078a4135aa.png">

**Describe the solution you'd like**
Either default to sorting files in the `File Preview` alphabetically or an option to specify how the files should be sorted.

**Describe alternatives you've considered**
Disabling the preview window. 😅

**Additional context**
I've searched high and low for any information about how the sorting works and how to change it. It's entirely possible that I'm missing something obvious, but I've looked through the docs, open and closed issues, experimented with how `ls` and `fd` display the files in my terminal, and searched through the telescope docs to see if there's a way to customize it from there.

I've made no changes to `file_browser`'s defaults in telescope's call to `setup`, but here's the user command I created to open `file_browser`:  

```lua
vim.api.nvim_create_user_command(
	"Dir",
	function()
		telescope.extensions.file_browser.file_browser({
			path = "%:p:h",
			grouped = true,
			hidden = true,
			dir_icon = "",
		})
	end,
	{}
)
```

**Comment by jamestrew** [comment]
I believe the file preview for directories for `file_browser` is just reusing `telescope`'s `file_previewer` previewer. Which is using `plenary`'s `ls_async` under the hood which doesn't really support sorting of any kind besides grouping directories and files.

I think I'd like this enhancement as well but it's two streams up from `telescope-file-browser` and wouldn't be as simple as adding a new option to `telescope-file-browser`. Doubly so since `plenary` is seldom adding new features these days.

**Comment by fdschmidt93** [comment]
Closing this as `wontfix` from within `telescope-file-browser.nvim`. It would require quite a broad set of deeper changes upstream for what I believe is a very idiosyncratic set of utility.

Strictly speaking, I guess you could monkey patch the `plenary.scandir.ls_async` function, but I guess that very messy.
