### ISSUE TITLE
Allow description inside mappings

### ISSUE THREAD

**Issue by lodisy** [nvim-telescope/telescope-file-browser.nvim#203]
**Is your feature request related to a problem? Please describe.**
Hello, I am not sure if it's possible to add description for each mapping inside the config?

Thus, I could use `telescope.builtin.keymaps` to find each operation?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jamestrew** [comment]
Are you talking about mappings such as those for actions (move, rename, copy, etc) within the `file_browser` telescope picker?

If so, no, there is currently no way to add description to the mappings. Adding a feature like that would probably come from upstream (`telescope.nvim`).
And even if there were, the mappings would not show up in `telescope.builtin.keymaps` since the mappings are only local to the picker window and don't exist when the picker isn't open.

The closest thing to want you're looking for that we can offer right now is the `which-key` feature that built into all telescope pickers. You can hit `<C-/>` in insert mode or `?` in normal mode (by default) to see a list of mappings attached to the picker.

**Comment by lodisy** [comment]
Hello, yes but thanks anyway.

Yeah I would dig more about this, I also find the `nvim-mapper` plugin may suit in this case as well.
