### ISSUE TITLE
Show Git status on files and folders

### ISSUE THREAD

**Issue by jan-xyz** [nvim-telescope/telescope-file-browser.nvim#214]
**Is your feature request related to a problem? Please describe.**
I would like to quickly see paths that have modifications or are newly added so that I quickly see the current state of my work.

**Describe the solution you'd like**
Have git status indicators on the paths that are changed, similar to other file-browsers (nvim-tree, nerdtree, etc.)

**Describe alternatives you've considered**
Use `Telescope git_status`, however, I would like to have a single command to open the file overview and increase information density.

**Additional context**

File status with `Telescope git_status`
<img width="1532" alt="Screenshot 2022-12-30 at 15 24 32" src="https://user-images.githubusercontent.com/5249233/210080552-708a4f77-35cb-4c88-b79e-1a37c07d7da2.png">

**Comment by jamestrew** [comment]
Seems like a decent idea. I will look into this.

**Comment by jan-xyz** [comment]
I can also help with the implementation myself. I am just new to the code base and would need some guidance maybe for starting points and implementation approach.

**Comment by fdschmidt93** [comment]
Sure, happy to have this!

> I can also help with the implementation myself. 

Sounds great! With my prior experience, it'd be actually quite easy and I'm happy to do this eventually as part of the large RFC in #210. I'd probably do it synchronously and just parse it efficiently as git status seems to be relatively fast (~5ms)

```lua

local bench = require "plenary.benchmark"
local Job = require "plenary.job"

local function git_status_for_folder()
  local entries, _ = Job:new({ command = "git", args = { "status", "-s", "." } }):sync()
  return entries
end

local function git_status_for_file(file)
  local entries, _ = Job:new({ command = "git", args = { "status", "-s", ".", "--", file } }):sync()
  return entries
end

bench("lua vs c ffi", {
  warmup = 10,
  runs = 50,
  fun = {
    {
      "git status for file",
      function()

        git_status_for_file $YOUR_FILE
      end,
    },
    {
      "git status for folder",
      function()
        -- return fd()
        git_status_for_folder()
      end,
    },
  },
})
```

I'm also happy to let you have a shot and guide you towards a PR though :)

On a high-level:

a) look at https://github.com/nvim-telescope/telescope.nvim/blob/a606bd10c79ec5989c76c49cc6f736e88b63f0da/lua/telescope/builtin/__git.lua#L306-L338
b) telescope's entry maker to parse the output for each file and render it in the results buffer: https://github.com/nvim-telescope/telescope.nvim/blob/a606bd10c79ec5989c76c49cc6f736e88b63f0da/lua/telescope/make_entry.lua#L1302-L1355

For means of background on how finder entry maker etc relate to one another, telescope docs have an overview of the architecture `:h telescope.nvim` (architectural overview is amongst first things).

The make entry logic would have to be ported to the `telescope-file-browser` logic. A PR doesn't need to be that polished because I'd probably merge it into the RFC PR (#210 is going to be very big and clean up a lot - also the entry maker to some degree, but quite exciting stuff :)

Hope that helps, let me know in case you need more input!

**Comment by jan-xyz** [comment]
@fdschmidt93 Thanks for the pointers they were already really helpful!

I was wondering if the `make_entry` function should rather fetch the git status when it makes the entries? I would need to somehow think anyways about how to merge the unchanged files with the ones that I get back from `git status`. That way it could be similarly implemented to the `display_stats` functionality.
