### ISSUE TITLE
Expand node

### ISSUE THREAD

**Issue by bjufre** [nvim-telescope/telescope-file-browser.nvim#264]
**Is your feature request related to a problem? Please describe.**
I found this plugin and wanted to use it to switch from a normal tree/drawer file explorer kinda thing. And so far it has been great, but one thing that I do miss though is the ability to stay in the context when "opening a folder" and instead have the folder/node expand and show me what's inside. I tried finding a way to configure this but haven't found it (I might've missed it though).

**Describe the solution you'd like**
Have the option to expand folders instead of navigating into them.

**Comment by fdschmidt93** [comment]
https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/210

This branch implements just that. I like to use it, but it's still WIP and you might run into bugs here or there (nothing mega critical). Happy to have more testers and fix issues along the way.

Eventually this will make it to master, but it's essentially implementation-wise and entirely different plugin. Without prolonged testing, I wouldn't feel comfortable merging this into master. I might actually make it a separate plugin since it's just easier, as file-browser as is just works.

**Comment by bjufre** [comment]
@fdschmidt93 I will take a look and test the branch!! Thank you very much for the quick response man!!!

When you say create another plugin, you mean another telescope extension with the same functionality but tree like?

**Comment by fdschmidt93** [comment]
> When you say create another plugin, you mean another telescope extension with the same functionality but tree like?

Yes, carve out that branch as a new plugin, since the back-end implementation is practically a different plugin.

Semantic versioning here is somewhat orthogonal, since configuration changes on key levels.

**Comment by bjufre** [comment]
I will close the issue since this has been answered in detail and we might have a different plugin after all, thank you @fdschmidt93 🙏
