### ISSUE TITLE
Update default icon after nerd fonts update

### ISSUE THREAD

**Issue by ema2159** [nvim-telescope/telescope-file-browser.nvim#279]
Hello! A couple of weeks ago, some breaking changes were introduced into the nerd fonts' repo. It would be good if the default `dir_icon` was updated accordingly. Currently, the following icon is set: "". I am not exactly sure but I think the icon has to be set to the following in order to look as similar as possible to the previous icon before the breaking changes: "" (please check the icons in Neovim with the most recent version of Nerd Fonts).

I am not submitting a PR because the change is trivial enough, as it should be just replacing the icon in [this](https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/fc70589a93d7bb42f4671ad75c8628a29995bcbe/lua/telescope/_extensions/file_browser/make_entry.lua#LL142C1-L142C1) line.

Thanks!

**Comment by jamestrew** [comment]
Is the icon broken for you or just different from what it used to be?

**Comment by ema2159** [comment]
Just looks different from what it used to. It's pretty easy to fix from the configuration, but I think it may be a good idea to change it to what it used to look. I am not sure if we are seeing the same, so I will post a screenshot tomorrow when on my computer.

**Comment by jamestrew** [comment]
Ok yeah it's been a while since I updated my nerdfont icons to the latest v3.0. I think I do remember the folder icon changing.

I get what you mean about retaining a similar if not the same look between the nerdfont versions but I don't really want the burden of maintaining parity through various nerdfont versions, comparing bunch of similar looking but slightly different icons for different versions of nerdfont. I don't know why nerdfont had to go and change the look :shrug: 

But yeah if you have a strong preference, you can override the default with the option `dir_icon`. I think technically `` (nf-oct-file_directory_fill) is the closest looking one to the previous one.

**Comment by ema2159** [comment]
I agree, nerdfonts performing such a change didn't make much sense to me either. However, they shouldn't be changing much, since I don't see nerd-fonts hoping from major version to major version that often. I would still perform the update, considering it is a simple enough change to perform and that other plugins have also been catching up with the recent changes in nerd-fonts.

It is up to you whether you want to perform the update or not though.
