### ISSUE TITLE
Mac keybindings 

### ISSUE THREAD

**Issue by N214** [nvim-telescope/telescope-file-browser.nvim#305]
Hello,

Anyone on Mac here, I couldn't find anything on the documentation, so asking here.
How do you use these command on macOS? 
<A-c>
<A-d>
<A-m>

Thank you

**Comment by jamestrew** [comment]
Key bindings are operating system agnostic.

You can do `:Telescope file_browser` to start. You can map this command to any key binding you prefer like so

```lua
vim.api.nvim_set_keymap(
  "n",
  "<space>fb",
  ":Telescope file_browser<CR>",
  { noremap = true }
)
```

The readme and the help docs for this plugin and telescope has more info on mappings for actions, etc. I can't link right now since I'm on mobile but hopefully you're able to find the info necessary.

**Comment by N214** [comment]
Thank you for your answer. I end up remapping the meta key from the terminal itself.
