### ISSUE TITLE
Custom `fd` args

### ISSUE THREAD

**Issue by MithicSpirit** [nvim-telescope/telescope-file-browser.nvim#326]
**Is your feature request related to a problem? Please describe.**
I have `.ignore` files in some places to prevent regular `fd` searches from having some files show up, but I don't want telescope-fb to ignore these files.

**Describe the solution you'd like**
I would like to use the `--no-ignore` flag to tell `fd` to not heed the `.ignore`. Since there are no current options to do this, I believe that the best way would be to add an option for arguments that should be passed to `fd`. This would also overall increase flexibility.

**Describe alternatives you've considered**
- I could just use a `.gitignore`, but that'd annoy me since this isn't a git repo;
- Changing `respect_gitignore` to use `--no-ignore` (instead of `--no-ignore-vcs`), but then the name isn't accurate and there would be significantly different behavior between fd and other backend(s?);
- Adding a new option for `--no-ignore` (separate from `respect_gitignore`), but then the interaction between this option and `respect_gitignore` is unintuitive for new users.

**Comment by jamestrew** [comment]
I open to adding a `no_ignore` option.

Little bit hesitant about allowing full control over the all fd args since the picker can't handle that.
Also I want to maintain some capability and feature parity between people using fd and those who don't (to be honest, I want to eventually make fd a hard requirement to simply things like this).
