### ISSUE TITLE
remove current folder from results

### ISSUE THREAD

**Issue by max397574** [nvim-telescope/telescope-file-browser.nvim#51]
I don't think this is a bug but I rly don't like it
I'm in my neovim config and use telescope file browser.
the results look sth like this:
![Screenshot 2022-01-11 at 11 14 01](https://user-images.githubusercontent.com/81827001/148923817-88fb0bab-f7c1-4e7a-9f9a-ca777431df2f.png)

Is it possible to get rid of the `../nvim_config` in from of every result? 
Perhaps make this configurable

**Comment by fdschmidt93** [comment]
First off, please put more effort in your issue. Don't circumvent the issue template due to laziness. That said, it's most likely something with your `path_display` configuration. I don't see `path_display` and don't get the `..` prefix on files, only for the parent folder.

Closing. Please open a proper issue with repro configuration. Thanks.
