### ISSUE TITLE
Having to confirm twice on operation cancel 

### ISSUE THREAD

**Issue by tami5** [nvim-telescope/telescope-file-browser.nvim#87]
### Description

This is annoying a bit. the second line printed makes the prompt stay there instead of just be printed in console.
![Screen Shot 2022-01-26 at 3 04 36 PM](https://user-images.githubusercontent.com/65782666/151159978-ed5e5810-c6d4-4339-a782-936510686d04.png)

maybe differing results would make sense and solve this?

### Neovim version

```markdown
NVIM v0.6.1
```

### Operating system and version

macOs

### Steps to reproduce

1. create/rename/delete
2. cancel or confirm 
3. console await user input

### Expected behavior

after confirming or canceling action the focus should be back on the browser

### Actual behavior

Await additional input.

### Minimal config

```Lua
..
```

**Comment by fdschmidt93** [comment]
I'd hope that this would be resolved by switching towards notifications?

#72 

I have to setup notifications and take a look at that PR.

**Comment by tami5** [comment]
I guess it would be a by product of #72.

**Comment by jamestrew** [comment]
Unfortunately #72 doesn't solve this `Press ENTER or type command to continue` issue.

I'll look into it a bit more within the next couple of days. All I know is that stacking too many multline `vim.notify` or `print` beyond the `cmdheight` is the culprit. I'm not super sure how to force clear what's in the command bar besides throwing a `vim.api.nvim_command('norm :esc<CR>')` between the `vim.notify`s which feels very janky and dumb.

**Comment by tami5** [comment]
Hmmm maybe then no new lines? flat text

**Comment by fdschmidt93** [comment]
So I've been cleaning up my dots a bit and also finally got around to installing `nvim-notify` and playing with that a bit.

I'll probably take over #72 eventually with my own PR (though borrowing some ideas :), from what I can tell there's two-three options here:
- swapping `vim.notify` with `nvim-notify`
- increasing `cmdheight` intermittently (a bit messy)
- Put messages into 1 line (as will my refactor) and then `vim.cmd [[ redraw! ]]` seems to work such that the 1 line solely remains in `cmdline`

As I understand it, `hit-enter` prompt is essentially triggering the redraw as it's otherwise not clear for `(n)vim` how to handle intermediate excess `cmdheight`.

**Comment by fdschmidt93** [comment]
This should hopefully be addressed now, so closing :)

Please let me know otherwise.
