### ISSUE TITLE
CD to git root directory

### ISSUE THREAD

**Issue by phortonssf** [nvim-telescope/telescope-file-browser.nvim#88]
**Is your feature request related to a problem? Please describe.**
Easier way to change nvim cwd to git root using the file browser

**Describe the solution you'd like**
While in file_browser, C-r would change cwd to git root directory or some other keybind

**Describe alternatives you've considered**
Using vim fugitve then using telescope file_browswer.

**Additional context**

**Comment by fdschmidt93** [comment]
Does this implement what you are looking for?

```lua
require "telescope".setup {
  extensions = {
    mappings = {
      i = { 
        ["<C-r>"] = function(prompt_bufnr)
          local git_root_path =
            require("plenary.job"):new({ command = "git", args = { "rev-parse", "--show-toplevel" } }):sync()[1]
          local current_picker = require("telescope.actions.state").get_current_picker(prompt_bufnr)
          local finder = current_picker.finder
          if finder.files then
            finder.path = git_root_path
          else
            finder.cwd = git_root_path
          end
          require("telescope._extensions.file_browser.utils").redraw_border_title(current_picker)
          current_picker:refresh(finder, { reset_prompt = true, multi = current_picker._multi })
        end
      }
    }
  }
}

```

**Comment by ikerurda** [comment]
I think running from the finder.path instead of vim's cwd would be better (cwd option in plenary.Job).
And I would suggest we check if the folder is a git repository before changing the path.


```lua
function(prompt_bufnr)
  local current_picker = require("telescope.actions.state").get_current_picker(prompt_bufnr)
  local finder = current_picker.finder
  local git_root_path = require("plenary.job"):new({
    command = "git",
    args = { "rev-parse", "--show-toplevel" },
    cwd = finder.path,
  }):sync()[1]
  if not git_root_path then
    print "[telescope] Not in a git repository"
    return
  end
  finder.cwd = git_root_path
  require("telescope._extensions.file_browser.utils").redraw_border_title(current_picker)
  current_picker:refresh(finder, { reset_prompt = true, multi = current_picker._multi })
end
```

Also, I'm not sure about this:
> ```lua
> if finder.files then
>   finder.path = git_root_path
> else
>   finder.cwd = git_root_path
> end
> ```
I would expect this action to only change the cwd, not the path.
If we consider adding this to `telescope-file-browser`, I think we should differentiate cwd_to_git_repo and goto_git_repo.

**Comment by fdschmidt93** [comment]
> I think running the command from the finder.path instead of vim's cwd would be better (cwd option in plenary.Job).

Good point :) whipped this up super quick.

> I would expect this action to only change the cwd, not the path.

That one is really tricky; I'd actually guess that most users would expect to change the `file_browser` to git root.

>  I think we should differentiate two actions: cwd_to_git_repo and goto_git_repo.

I have to think about this some more; ideally I'd only want to have one action for these sorts of things to avoid confusion and cluttering `fb_actions`. Then again, you'd always kind of have to make assumptions as to what the user wants.

I'm inclined to design these sorts of aspects more as a library for users to create their own actions for which they just have to pass the path (for which we can have separate utility functions to be created) and then users just create their own actions. We would otherwise always run in these sorts of discussions.

**Comment by thyeun** [comment]
Sorry for asking here, meaning that to avoid error message as below, i have to start ```nvim``` inside the git repos folder than only ```git status``` will appear correctly?

![Screenshot_2023-05-31-01-00-28_29879](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/1939446/26088caa-921d-4de7-93e0-9b528770b578)

**Comment by jamestrew** [comment]
@thyeun sorry i'm not understanding the context of your issue. i can help you if you create a new issue with steps to reproduce.

**Comment by thyeun** [comment]
@jamestrew is ok, since Nvchad already answer.
